Nama =   input("Nama                 :")
NIM =    input("NIM                  :")
KP =     input("Kelas Paralel        :")
TTL =    input("Tempat/Tanggal Lahir :")
Alamat = input("Alamat               :")
Hobby =  input("Hobby                :")
NO =     input("No. HP               :")

print("")
print("Nama                  :",Nama)
print("NIM                   :",NIM)
print("Kelas Paralel         :",KP)
print("Tempat/Tanggal Lahir  :",TTL)
print("Alamat                :",Alamat)
print("Hobby                 :",Hobby)
print("No. HP                :",NO)